import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const bebas = Bebas_Neue({
 
  subsets: ["latin"],
  weight: "400",
});
const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar></NavBar>
        
        <main className="w-11/12 mx-auto">
          {children}
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
export { bebas };